# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--memory", "8192"]
    vb.customize ["modifyvm", :id, "--cpus", "8"]
  end

  # Set system configurations
  config.vm.provision(
    :shell,
    path: 'configs/system.sh',
  )

  config.vm.synced_folder "nvim-configs", "/root/.config/nvim"
end

